# .travis.yml
language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

script:
  - make test
  - make integration-test
  # teste that it is possible to compile fuzzer function
  - make test-fuzzing

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
